// Filename: stackrecursion.cpp
//
// The file basically contains a number of string functions that are "fundamentally" (or naturally) recursive,
// but are implemented with a stack.
// 
// The functions are: generating all stretches, generating all anagrams, generating the language from a string.
// For details about these functions, refer to the file stackrecursion_qns.pdf.
// 
// Each of these functions returns a list of strings. The main code only calls one of these functions,
// and the remaining calls are commented out. You can uncomment the function you want.
// Finally, the code sorts the list by lexicographic order, and prints the strings to the output file (each in a separate line).
// 
// The code uses the List data structure used in a number of CSE101 assignments and tests.
// 
// USAGE:  (the executable is generated by a Makefile)
//     ./stackrecursion <INPUT FILE> <OUTPUT FILE>
// 
//     The first line of <INPUT FILE> is read, as a string. The second line is optionally read as an int, if the desired
// function (language, stretch) requires an int argument. Again, all of this is hardcoded, so you need to comment/uncomment
// the desired lines to run different functions. <OUTPUT FILE> contains all subsequences, each in a separate line.
// 
// 
// C. Seshadhri, Jan 2020

#include <iostream>
#include "list.h"
#include <stack>
#include <stdexcept>
#include <fstream>
#include <array>
#include <vector> 
#include <algorithm>
#include <sstream>
using namespace std;


// This class keeps pairs of string. This may be useful for simulating the recursion through as stack.
class Pair
{
    public:
        string in_str;
        string fixed_str;
};


 // This function generates all anagrams/permutations of the input in_str, and outputs them as a list. This function does not use recursion.
// Input: string in_str
// Output: list of all anagrams of in_str

List allAnagrams(string input_str)
{
    List results;
    stack<Pair> build;
    build.push({input_str, ""});
    //int count = 0;

    while(!build.empty())// && count < 30)
    {
        //cout << "Pair: " << build.top().in_str << ", ";
        //cout << build.top().fixed_str << endl;
        //count++;
        Pair curr = build.top();
        build.pop();

        if(curr.in_str.empty())
        {
            //cout << "true: " << curr.fixed_str << endl;
            results.insert(curr.fixed_str);
        }
        else
        {
            //cout << curr.in_str.length() << endl;
            for(int i = 0; i < curr.in_str.length(); i++)
            {
                string newFixed = curr.fixed_str + curr.in_str[i];
                string newIn = curr.in_str.substr(0, i) + curr.in_str.substr(i+1);
                //cout << "inserting pair: " << newIn << ", " << newFixed << endl;

                build.push({newIn, newFixed});
            }
        }
    }
    return results;
}




int main(int argc, char** argv)
{
    if (argc < 3) // must provide two arguments as input
    {
        throw std::invalid_argument("Usage: ./stackrecursion <INPUT FILE> <OUTPUT FILE>"); // throw error
    }

    ifstream input; // stream for input file
    ofstream output; // stream for output file

    input.open(argv[1]); // open input file
    output.open(argv[2]); // open output file

    string in_str; // to store the input string from the file

    getline(input, in_str); // get the single string from the input file

    List myList = allAnagrams(in_str); // generate all anagrams and store in the linked list

    myList.sort(); // sort the list
    
    output << myList.print("\n") << endl;  // print the list, using a new line as delimiter between items of the list
    //output.flush();
    myList.deleteList(); // free all the memory of this list

    input.close(); // close the I/O files
    output.close();
}
